### ISSUE TITLE
train failed

### ISSUE THREAD

**Issue by no5-hao** [HamPerdredes/SOOD#14]
Thanks for your wonderful work, I want to know how to train on a single GPU, not distributed training. I failed to train on a single gpu?

**Comment by BYbirdy** [comment]
May I ask if it has been resolved? I have the same problem.

**Comment by HamPerdredes** [comment]
The following command could be helpful, i.e., apply distributed training for single card.

CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nnodes=1 \
--node_rank=0 --master_addr="127.0.0.1" --nproc_per_node=1 --master_port=25500 \
train.py configs/ssad_fcos/sood_fcos_dota15_10per.py \
--launcher pytorch \
--work-dir xxx

**Comment by 1shenhui** [comment]
i use the comment with nohup but encountered problems. the process of training interrupted suddenly
