### ISSUE TITLE
loss_gc_unsup始终为0？

### ISSUE THREAD

**Issue by dingdingyu123321** [HamPerdredes/SOOD#2]
非常棒的工作，但我训练过程中发现loss_gc_unsup始终为0，是什么情况，不知您是否出现过。

**Comment by HamPerdredes** [comment]
你好，这是正常的，loss_gc_unsup是基于最优传输计算得到的代价求导得到梯度后，再乘上模型参数得到的，这与一般的loss计算方式是不同的，更进一步，可以参考[这里](https://github.com/cvlab-stonybrook/DM-Count/issues/16)
