### ISSUE TITLE
只打印模型不训练以及训练结束后验证的时候报错

### ISSUE THREAD

**Issue by Yang-yimin** [HamPerdredes/SOOD#27]
作者您好，感谢您非常nice的工作，我遇到了这样一个问题，在模型训练时（使用ssad.apis中的train_detector）打印完毕模型结构后会一直停在那里，如图所示
![1111](https://github.com/HamPerdredes/SOOD/assets/59383708/36a6868e-0d6c-4107-9bc9-76ed85810fa0)

当我更改为mmrotate.apis中的train_detector时则会报这样的错误：模型在训练的前3200iter正常，但是进行验证时出错，如图所示：
![微信截图_20240322193922](https://github.com/HamPerdredes/SOOD/assets/59383708/652c4069-0cf6-4471-bef5-5ceb55e155a6)

烦请您在百忙之中点拨一下，以下为我的环境：
```python
mmcv-full                 1.7.2                    pypi_0    pypi
mmdet                     2.28.2                   pypi_0    pypi
mmengine                  0.10.3                   pypi_0    pypi
mmrotate                  0.3.4                     dev_0    <develop>
model-index               0.1.11                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
nettle                    3.7.3                hbbd107a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nsight-compute            2024.1.0.13                   0    nvidia
numpy                     1.26.4           py39h5f9d8c6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.26.4           py39hb5e798b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opencv-python             4.9.0.80                 pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openjpeg                  2.4.0                h3ad879b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.0.13               h7f8727e_0    defaults
openxlab                  0.0.36                   pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 24.0                     pypi_0    pypi
pandas                    2.2.1                    pypi_0    pypi
pillow                    10.2.0           py39h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       23.3.1           py39h06a4308_0    defaults
platformdirs              4.2.0                    pypi_0    pypi
prettytable               3.5.0            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
protobuf                  4.25.3                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python                    3.9.18               h955ad1f_0    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch                   1.13.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
pytorch-mutex             1.0                        cuda    pytorch

**Comment by Yang-yimin** [comment]
使用单卡训练也会出现同样的问题

**Comment by Yang-yimin** [comment]
谢谢，这个问题已解决

**Comment by GuGuLL123** [comment]
我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢

**Comment by Yang-yimin** [comment]
> 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢

您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的

**Comment by GuGuLL123** [comment]
谢啦，我应该是mmcv和mmdet的版本问题，我把版本换成cuda111/116: mmcv-1.6.1 mmdet-2.x mmrotate 0.x  就好了

**Comment by CaptainRoby** [comment]
> > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> 
> 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的

你好，请问什么是作者修改版得train.py 呢，调用的api哪些不同呢？我也遇到了这个问题没能解决。

**Comment by Yang-yimin** [comment]
> > > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> > 
> > 
> > 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的
> 
> 你好，请问什么是作者修改版得train.py 呢，调用的api哪些不同呢？我也遇到了这个问题没能解决。

你可以用VS code对比查看

**Comment by IamMichaelMeng** [comment]
> > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> 
> 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的

您好，请问您是运行了ssad/apis/train.py才解决问题的吗？如果是的话，我在运行ssad/apis/train.py的时候报错ImportError: attempted relative import with no known parent package，报错位置是/ssad/apis/train.py 中的 from ..datasets.builder import build_dataloader，请问您遇到过吗？如果遇到过，您又是如何解决的呢？

**Comment by IamMichaelMeng** [comment]
> > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> 
> 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的

您好，脑前打扰您，我遇到了和您一样的问题，请问您这边能不能详细展开说说您是如何解决问题的呢？您的回复对于我来说十分地重要。

**Comment by IamMichaelMeng** [comment]
> > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> 
> 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的

您好，冒昧打扰您，我遇到了和您一样的问题，请问您这边能不能详细展开说说您是如何解决问题的呢？您的回复对于我来说十分地重要。

**Comment by Yang-yimin** [comment]
> > > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> > 
> > 
> > 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的
> 
> 您好，请问您是运行了ssad/apis/train.py才解决问题的吗？如果是的话，我在运行ssad/apis/train.py的时候报错ImportError: attempted relative import with no known parent package，报错位置是/ssad/apis/train.py 中的 from ..datasets.builder import build_dataloader，请问您遇到过吗？如果遇到过，您又是如何解决的呢？

您好，运行的应该是最外边哪个train.py,不是ssad里边那个

**Comment by IamMichaelMeng** [comment]
> > > > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> > > 
> > > 
> > > 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的
> > 
> > 
> > 您好，请问您是运行了ssad/apis/train.py才解决问题的吗？如果是的话，我在运行ssad/apis/train.py的时候报错ImportError: attempted relative import with no known parent package，报错位置是/ssad/apis/train.py 中的 from ..datasets.builder import build_dataloader，请问您遇到过吗？如果遇到过，您又是如何解决的呢？
> 
> 您好，运行的应该是最外边哪个train.py,不是ssad里边那个

是的，我发现了ssad里面的train，最近我是刚刚切换到这个研究领域内，我不清楚ssad里面的train的启动命令该如何写才是正确、才能让模型顺利启动运行起来，您这边方便详细说一下吗？真心恳请大佬指导一下，您的解答真得会帮助到我很多很多。

**Comment by Yang-yimin** [comment]
> > > > > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> > > > 
> > > > 
> > > > 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的
> > > 
> > > 
> > > 您好，请问您是运行了ssad/apis/train.py才解决问题的吗？如果是的话，我在运行ssad/apis/train.py的时候报错ImportError: attempted relative import with no known parent package，报错位置是/ssad/apis/train.py 中的 from ..datasets.builder import build_dataloader，请问您遇到过吗？如果遇到过，您又是如何解决的呢？
> > 
> > 
> > 您好，运行的应该是最外边哪个train.py,不是ssad里边那个
> 
> 是的，我发现了ssad里面的train，最近我是刚刚切换到这个研究领域内，我不清楚ssad里面的train的启动命令该如何写才是正确、才能让模型顺利启动运行起来，您这边方便详细说一下吗？真心恳请大佬指导一下，您的解答真得会帮助到我很多很多。

你可以参考readme里的内容，有进行训练的命令行指令

**Comment by IamMichaelMeng** [comment]
我尝试按照README里的命令，并切换成ssad里面的train.py，但是这时候输入命令，敲下回车后，程序就会自动终止，无法正常启动训练过程，请问您遇到过吗？我使用的命令如下，您能帮忙看一下吗？是不是我的命令哪里有问题？谢谢您！
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nnodes=1 \
--node_rank=0 --master_addr="127.0.0.1" --nproc_per_node=2 --master_port=25500 \
ssad/apis/train.py configs/ssad_fcos/sood_fcos_dota15_10per.py \
--launcher pytorch \
--work-dir ./work_dir/

**Comment by IamMichaelMeng** [comment]
> > > > > > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> > > > > 
> > > > > 
> > > > > 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的
> > > > 
> > > > 
> > > > 您好，请问您是运行了ssad/apis/train.py才解决问题的吗？如果是的话，我在运行ssad/apis/train.py的时候报错ImportError: attempted relative import with no known parent package，报错位置是/ssad/apis/train.py 中的 from ..datasets.builder import build_dataloader，请问您遇到过吗？如果遇到过，您又是如何解决的呢？
> > > 
> > > 
> > > 您好，运行的应该是最外边哪个train.py,不是ssad里边那个
> > 
> > 
> > 是的，我发现了ssad里面的train，最近我是刚刚切换到这个研究领域内，我不清楚ssad里面的train的启动命令该如何写才是正确、才能让模型顺利启动运行起来，您这边方便详细说一下吗？真心恳请大佬指导一下，您的解答真得会帮助到我很多很多。
> 
> 你可以参考readme里的内容，有进行训练的命令行指令

前辈，真的请麻烦您指导点拨一下吧，我已经被这个问题困扰了好多天了，真得不知道该怎么办了，您就指导一下我好不好，我遇到了和您一模一样的问题，但是我真得不知道怎么样才能启动ssad/apis/traim.py，到底怎么样才能让模型顺利运行起来啊，孩子真得快崩溃了！我按照README的启动命令去运行ssad里面的train.py，结果项目直接闪退，根本就无法运行，我是真的不知道问题出在哪里了，麻烦您指导点播一下吧，感谢您！

**Comment by Yang-yimin** [comment]
> > > > > > > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> > > > > > 
> > > > > > 
> > > > > > 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的
> > > > > 
> > > > > 
> > > > > 您好，请问您是运行了ssad/apis/train.py才解决问题的吗？如果是的话，我在运行ssad/apis/train.py的时候报错ImportError: attempted relative import with no known parent package，报错位置是/ssad/apis/train.py 中的 from ..datasets.builder import build_dataloader，请问您遇到过吗？如果遇到过，您又是如何解决的呢？
> > > > 
> > > > 
> > > > 您好，运行的应该是最外边哪个train.py,不是ssad里边那个
> > > 
> > > 
> > > 是的，我发现了ssad里面的train，最近我是刚刚切换到这个研究领域内，我不清楚ssad里面的train的启动命令该如何写才是正确、才能让模型顺利启动运行起来，您这边方便详细说一下吗？真心恳请大佬指导一下，您的解答真得会帮助到我很多很多。
> > 
> > 
> > 你可以参考readme里的内容，有进行训练的命令行指令
> 
> 前辈，真的请麻烦您指导点拨一下吧，我已经被这个问题困扰了好多天了，真得不知道该怎么办了，您就指导一下我好不好，我遇到了和您一模一样的问题，但是我真得不知道怎么样才能启动ssad/apis/traim.py，到底怎么样才能让模型顺利运行起来啊，孩子真得快崩溃了！我按照README的启动命令去运行ssad里面的train.py，结果项目直接闪退，根本就无法运行，我是真的不知道问题出在哪里了，麻烦您指导点播一下吧，感谢您！

您好，运行的应该是最外边哪个train.py,不是ssad里边那个，先不用管那个

**Comment by IamMichaelMeng** [comment]
> > > > > > > > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的
> > > > > > 
> > > > > > 
> > > > > > 您好，请问您是运行了ssad/apis/train.py才解决问题的吗？如果是的话，我在运行ssad/apis/train.py的时候报错ImportError: attempted relative import with no known parent package，报错位置是/ssad/apis/train.py 中的 from ..datasets.builder import build_dataloader，请问您遇到过吗？如果遇到过，您又是如何解决的呢？
> > > > > 
> > > > > 
> > > > > 您好，运行的应该是最外边哪个train.py,不是ssad里边那个
> > > > 
> > > > 
> > > > 是的，我发现了ssad里面的train，最近我是刚刚切换到这个研究领域内，我不清楚ssad里面的train的启动命令该如何写才是正确、才能让模型顺利启动运行起来，您这边方便详细说一下吗？真心恳请大佬指导一下，您的解答真得会帮助到我很多很多。
> > > 
> > > 
> > > 你可以参考readme里的内容，有进行训练的命令行指令
> > 
> > 
> > 前辈，真的请麻烦您指导点拨一下吧，我已经被这个问题困扰了好多天了，真得不知道该怎么办了，您就指导一下我好不好，我遇到了和您一模一样的问题，但是我真得不知道怎么样才能启动ssad/apis/traim.py，到底怎么样才能让模型顺利运行起来啊，孩子真得快崩溃了！我按照README的启动命令去运行ssad里面的train.py，结果项目直接闪退，根本就无法运行，我是真的不知道问题出在哪里了，麻烦您指导点播一下吧，感谢您！
> 
> 您好，运行的应该是最外边哪个train.py,不是ssad里边那个，先不用管那个
感谢前辈的回复，我现在又重新运行最外面的train，但是就是遇到了和您一样的情况，迭代到3200iter进入val的时候就报错，而且报错报的也和您一模一样，所以我就好奇您是怎么解决这个问题的。

**Comment by IamMichaelMeng** [comment]
> > > > > > > > > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，请问您是运行了ssad/apis/train.py才解决问题的吗？如果是的话，我在运行ssad/apis/train.py的时候报错ImportError: attempted relative import with no known parent package，报错位置是/ssad/apis/train.py 中的 from ..datasets.builder import build_dataloader，请问您遇到过吗？如果遇到过，您又是如何解决的呢？
> > > > > > 
> > > > > > 
> > > > > > 您好，运行的应该是最外边哪个train.py,不是ssad里边那个
> > > > > 
> > > > > 
> > > > > 是的，我发现了ssad里面的train，最近我是刚刚切换到这个研究领域内，我不清楚ssad里面的train的启动命令该如何写才是正确、才能让模型顺利启动运行起来，您这边方便详细说一下吗？真心恳请大佬指导一下，您的解答真得会帮助到我很多很多。
> > > > 
> > > > 
> > > > 你可以参考readme里的内容，有进行训练的命令行指令
> > > 
> > > 
> > > 前辈，真的请麻烦您指导点拨一下吧，我已经被这个问题困扰了好多天了，真得不知道该怎么办了，您就指导一下我好不好，我遇到了和您一模一样的问题，但是我真得不知道怎么样才能启动ssad/apis/traim.py，到底怎么样才能让模型顺利运行起来啊，孩子真得快崩溃了！我按照README的启动命令去运行ssad里面的train.py，结果项目直接闪退，根本就无法运行，我是真的不知道问题出在哪里了，麻烦您指导点播一下吧，感谢您！
> > 
> > 
> > 您好，运行的应该是最外边哪个train.py,不是ssad里边那个，先不用管那个
> > 感谢前辈的回复，我现在又重新运行最外面的train，但是就是遇到了和您一样的情况，迭代到3200iter进入val的时候就报错，而且报错报的也和您一模一样，所以我就好奇您是怎么解决这个问题的。

![image](https://github.com/user-attachments/assets/6737df1a-4b2d-4ef2-829b-be5de46109b9)
前辈您看，和您一模一样的错误，到底该如何才能解决这个问题啊？😭😭

**Comment by Yang-yimin** [comment]
> > > > > > > > > > 我也遇到了打印完毕模型结构就停着不懂的情况了，请问您是怎么解决的呢
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 您好，我在使用原版的train.py的时候也出现了这个情况，修改为作者修改版的train.py后解决，差别在与调用的api不同，后者是ssad中的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 您好，请问您是运行了ssad/apis/train.py才解决问题的吗？如果是的话，我在运行ssad/apis/train.py的时候报错ImportError: attempted relative import with no known parent package，报错位置是/ssad/apis/train.py 中的 from ..datasets.builder import build_dataloader，请问您遇到过吗？如果遇到过，您又是如何解决的呢？
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，运行的应该是最外边哪个train.py,不是ssad里边那个
> > > > > > 
> > > > > > 
> > > > > > 是的，我发现了ssad里面的train，最近我是刚刚切换到这个研究领域内，我不清楚ssad里面的train的启动命令该如何写才是正确、才能让模型顺利启动运行起来，您这边方便详细说一下吗？真心恳请大佬指导一下，您的解答真得会帮助到我很多很多。
> > > > > 
> > > > > 
> > > > > 你可以参考readme里的内容，有进行训练的命令行指令
> > > > 
> > > > 
> > > > 前辈，真的请麻烦您指导点拨一下吧，我已经被这个问题困扰了好多天了，真得不知道该怎么办了，您就指导一下我好不好，我遇到了和您一模一样的问题，但是我真得不知道怎么样才能启动ssad/apis/traim.py，到底怎么样才能让模型顺利运行起来啊，孩子真得快崩溃了！我按照README的启动命令去运行ssad里面的train.py，结果项目直接闪退，根本就无法运行，我是真的不知道问题出在哪里了，麻烦您指导点播一下吧，感谢您！
> > > 
> > > 
> > > 您好，运行的应该是最外边哪个train.py,不是ssad里边那个，先不用管那个
> > > 感谢前辈的回复，我现在又重新运行最外面的train，但是就是遇到了和您一样的情况，迭代到3200iter进入val的时候就报错，而且报错报的也和您一模一样，所以我就好奇您是怎么解决这个问题的。
> 
> ![image](https://private-user-images.githubusercontent.com/51892921/378438818-6737df1a-4b2d-4ef2-829b-be5de46109b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTY3MTAsIm5iZiI6MTcyOTUxNjQxMCwicGF0aCI6Ii81MTg5MjkyMS8zNzg0Mzg4MTgtNjczN2RmMWEtNGIyZC00ZWYyLTgyOWItYmU1ZGU0NjEwOWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEzMTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNmIzNDc1ZDg4MjY1MDc3YWM2MzE2ZTZjNjhlODgwNzc3MWI0N2E2OGM1NDJhZDVhYTAzNTA4ZmU1ZTFjZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yufWvVkJBcHKAty2rxAJM6oqfEji0dSeUkBpn5A58v8) 前辈您看，和您一模一样的错误，到底该如何才能解决这个问题啊？😭😭

你是训练了2100次以后出的问题，说明训练本身没事儿，是不是你测试的数据有问题呀，或者你自己的模型测试的代码有问题？具体我也记不太清楚了

**Comment by IamMichaelMeng** [comment]
代码是没问题的，因为我现在还没有动他的源代码。难道会是数据集的问题吗？我去检查一下数据集吧。

**Comment by IamMichaelMeng** [comment]
问题已解决，现将个人的解决方案更新如下：
首先，我的环境配置信息如下，其实主要就是mmcv-full和mmdet这两个包的版本：
python：3.8.19
cuda：11.3
pytorch：1.12.1
mmcv-full：1.6.0
mmdet：2.28.2
如果你遇到了其他的问题，比如说RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`大概率是包的版本不匹配。

其次，要在根目录下的tran.py中，**使用from ssad.apis import train_detector，而不是from mmrotate.apis import train_detector，这一步非常重要。**

最后，还是在train.py中，main()函数的末尾，在调用ttrain_detector()之前，加一句代码：
`if 'type' in cfg.evaluation:`
`       cfg.evaluation.pop('type')`
该行代码的作用是将cfg中的‘type’键值对去掉，这个‘type’键值对的存在就是导致TypeError: evaluate() got an unexpected keyword argument ‘type’问题的原因。

做出以上修改后，项目就可以正常运行了。
这个问题困扰了我三四天，大家在面对错误的时候，还是要仔细揣摩出给出的提示，深入思考导致该错误的原因以及位置。
