### ISSUE TITLE
Unable to get the results in the paper

### ISSUE THREAD

**Issue by Rsodlei** [HamPerdredes/SOOD#31]
Thank you for your innovative work. When I reproduce your model on 10% labeled data, the mAP is 47.37 (sliced data).I want to know whether the mAP of the DOTA-v1.5-val dataset in the paper are measured by the sliced data set or the merged data set.If it is sliced data set, can you provide me with your logs at that time for my study. set or the merged data set.If it is the sliced data set, can you provide me with your logs at that time for my study.
感谢您的创新性的工作。我在10%的有标注数据上复现您的模型时，mAP为47.37（sliced data）。我想知道论文中 DOTA-v1.5-val 数据集的 mAP 是通过切片数据集还是合并数据集测量的。如果是sliced data set，您能否提供您当时的日志供我学习。

**Comment by IamMichaelMeng** [comment]
Hello, thank you for your work, I have encountered difficulties in the data preparation stage, may I ask what are the specific steps of data preparation? How do I get the data ready to make the model work?

**Comment by Z-Z188** [comment]
> Thank you for your innovative work. When I reproduce your model on 10% labeled data, the mAP is 47.37 (sliced data).I want to know whether the mAP of the DOTA-v1.5-val dataset in the paper are measured by the sliced data set or the merged data set.If it is sliced data set, can you provide me with your logs at that time for my study. set or the merged data set.If it is the sliced data set, can you provide me with your logs at that time for my study. 感谢您的创新性的工作。我在10%的有标注数据上复现您的模型时，mAP为47.37（sliced data）。我想知道论文中 DOTA-v1.5-val 数据集的 mAP 是通过切片数据集还是合并数据集测量的。如果是sliced data set，您能否提供您当时的日志供我学习。

您好，请问环境是如何安装的呢，比如mmcv，mmdet的版本是啥呀，我安装了两三天还是没跑成功。希望大佬教教，谢谢！！！

**Comment by IamMichaelMeng** [comment]
我刚刚运行成功，请参考这个 issue #27 ，拉到最下面有我的详细配置。

**Comment by zlx913** [comment]
> 我刚刚运行成功，请参考这个 issue #27 ，拉到最下面有我的详细配置。

Excuse me,May I have your contact information please? I want to ask you some questions about SOOD training.
