### ISSUE TITLE
如何准备数据集

### ISSUE THREAD

**Issue by IamMichaelMeng** [HamPerdredes/SOOD#32]
十分感谢作者您的工作，但是我目前在数据准备阶段遇到了困难，我已经从DOTA官网下载了数据，但是我不知道如何处理数据才能让模型顺利运行起来，**您能详细说一下数据准备阶段的步骤是什么吗？**例如说split_data_via_list.py中的所提到的JSON文件指的是什么JSON文件？应该从哪里获取？DOTA官网上并没有提供JSON的文件。

**Comment by cvPerdredes** [comment]
您好，用于划分labeled和unlabeled的JSON文件位于项目的data_lists目录下。

**Comment by IamMichaelMeng** [comment]
感谢您的回复，我还有个问题，train_xx_labeled中的“xx”指的是10/20/30还是单纯的就是‘xx’？

**Comment by IamMichaelMeng** [comment]
谢谢作者回复，我还有个问题，数据集train负责训练，那么trainval数据集的作用是什么？

**Comment by cvPerdredes** [comment]
> 谢谢作者回复，我还有个问题，数据集train负责训练，那么trainval数据集的作用是什么？

用于全量数据的实验，即使用trainval作为labeled，使用DOTA-v2.0额外的数据作为unlabeled data。
