### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss.

### ISSUE THREAD

**Issue by zlx913** [HamPerdredes/SOOD#33]
how to solve this error?

**Comment by zlx913** [comment]
If I set parameter find_unused_parameters to TRUE, will it affect the training results?

**Comment by IamMichaelMeng** [comment]
I can't run this model on my computer, would you mind sharing the configuration details of your project? Especially the versions of mmcv-full, mmdet and mmrotate. Thank you so much.

**Comment by HamPerdredes** [comment]
Have you made some modification on the code ? Set "find_unused_parameters=True" in config file may solve this issue.

**Comment by zlx913** [comment]
> Have you made some modification on the code ? Set "find_unused_parameters=True" in config file may solve this issue.

Yes, I have resolved that issue. I wanted to apply your model to object detection, but unfortunately, it seems I didn't get the desired results.

**Comment by zlx913** [comment]
> I can't run this model on my computer, would you mind sharing the configuration details of your project? Especially the versions of mmcv-full, mmdet and mmrotate. Thank you so much.

https://github.com/HamPerdredes/SOOD/issues/27#issue-2202310680，you can refer this link

**Comment by HamPerdredes** [comment]
> > Have you made some modification on the code ? Set "find_unused_parameters=True" in config file may solve this issue.
> 
> Yes, I have resolved that issue. I wanted to apply your model to object detection, but unfortunately, it seems I didn't get the desired results.

Thanks for your exploration. The design of GC (based on optimal transport) maybe helpful for general object detection task, if objects' distribution shows some certain patterns. Please refer to our [extension](https://arxiv.org/abs/2407.01016) on SOOD if you are interest.
