### ISSUE TITLE
loss_gc_unsup一直为零

### ISSUE THREAD

**Issue by zlx913** [HamPerdredes/SOOD#34]
在我训练过程中，loss_gc_unsup打印的值一直为零，而且我用10%标注数据单卡跑出来的最好结果大概是0.463，估计是gcloss没起作用，但我不知道是什么原因导致的，期望作者能给点建议

**Comment by zlx913** [comment]
最好结果是0.476，写错了

**Comment by HamPerdredes** [comment]
gc部分的loss数值是很小的，量级大概是在1e-5左右。

关于模型性能，可能与卡数有关，论文中默认配置为两卡，此外可参考这个[issue](https://github.com/HamPerdredes/SOOD/issues/6)。

**Comment by IamMichaelMeng** [comment]
您好，请问datav15-v15only.py、datav15-val.py以及datav15.py三个文件的区别是什么？各自所负责的功能又是什么？此外，数据集trainval的作用又是什么？

**Comment by HamPerdredes** [comment]
> 您好，请问datav15-v15only.py、datav15-val.py以及datav15.py三个文件的区别是什么？各自所负责的功能又是什么？此外，数据集trainval的作用又是什么？

您好，这三个文件主要用于supervised baseline的训练，datav15-v15only.py和datav15-val.py这两个文件内容应该是一样的，对应的实验设置为使用dota-1.5-train作为训练集，并在dota-1.5-val上进行评测；datav15.py表示使用dota-1.5-trainval进行训练，并在dota-1.5-test上进行评测。
