### ISSUE TITLE
datav15-v15only.py、datav15-val.py以及datav15.py的区别。

### ISSUE THREAD

**Issue by IamMichaelMeng** [HamPerdredes/SOOD#35]
作者好，感谢您出色的研究工作。在我看您的源代码时，有一些疑惑，请问datav15-v15only.py、datav15-val.py以及datav15.py三个文件的区别是什么？各自所负责的功能又是什么？此外，数据集trainval的作用又是什么？感谢作者！期待您的回复。

**Comment by HamPerdredes** [comment]
您好，这三个文件主要用于supervised baseline的训练，datav15-v15only.py和datav15-val.py这两个文件内容应该是一样的，对应的实验设置为使用dota-1.5-train作为训练集，并在dota-1.5-val上进行评测；datav15.py表示使用dota-1.5-trainval进行训练，并在dota-1.5-test上进行评测。

**Comment by IamMichaelMeng** [comment]
感谢作者的回复，我还想问一下，“使用dota-1.5-trainval进行训练，在dota-1.5-test上进行评测”的目的是想验证什么？因为DOTAv1.5-test数据集是没有标注的，既然test没有标注，那么怎么做评测呢？

**Comment by IamMichaelMeng** [comment]
感谢作者的回复，这三个文件主要用于supervised baseline的训练，是不是说这三个文件不是给SOOD模型，而是给baseline用的，对吗？

**Comment by HamPerdredes** [comment]
是的，半监督过程中数据集的设置已经在对应的config文件中设置好了，例如[这里](https://github.com/HamPerdredes/SOOD/blob/3bf0add6fa7e5841ef2fb119f7c0caa7925d934b/configs/ssad_fcos/sood_fcos_dota15_10per.py#L10)。

**Comment by IamMichaelMeng** [comment]
感谢作者，我还有一个问题，您提到“datav15.py表示使用dota-1.5-trainval进行训练，并在dota-1.5-test上进行评测”。但是dota-1.5-test是没有标签的，既然没有没有标签，那评测的是什么？

**Comment by IamMichaelMeng** [comment]
> 您好，这三个文件主要用于supervised baseline的训练，datav15-v15only.py和datav15-val.py这两个文件内容应该是一样的，对应的实验设置为使用dota-1.5-train作为训练集，并在dota-1.5-val上进行评测；datav15.py表示使用dota-1.5-trainval进行训练，并在dota-1.5-test上进行评测。

感谢作者，我还有一个问题，您提到“datav15.py表示使用dota-1.5-trainval进行训练，并在dota-1.5-test上进行评测”。但是dota-1.5-test是没有标签的，既然没有没有标签，那评测的是什么？还有，如果我现在要对10%标注下模型性能进行评测，我是不是应该使用dotav15_10per.py而不是dotav15_val.py？期待您的回复。
