### ISSUE TITLE
The mAP of training

### ISSUE THREAD

**Issue by Luo-Z13** [HamPerdredes/SOOD#8]
Thank you for your wonderful work! However, I try to train at a scale of ten percent and did not achieve the level of effectiveness mentioned in the paper.The configuration file I used is as follows.

sys.platform: linux
Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA TITAN RTX
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.8
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.8.0
MMCV: 1.6.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMRotate: 0.3.2+962c9a6
------------------------------------------------------------

2023-08-23 23:23:09,110 - mmrotate - INFO - Distributed training: True
2023-08-23 23:23:10,673 - mmrotate - INFO - Config:
evaluation = dict(
    interval=3200,
    metric='mAP',
    type='SubModulesDistEvalHook',
    save_best='mAP')
optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333,
    step=[8, 11])
runner = dict(type='IterBasedRunner', max_iters=120000)
checkpoint_config = dict(interval=3200, by_epoch=False, max_keep_ckpts=2)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
detector = dict(
    type='SemiRotatedFCOS',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_output',
        num_outs=5,
        relu_before_extra_convs=True),
    bbox_head=dict(
        type='SemiRotatedFCOSHead',
        num_classes=16,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        strides=[8, 16, 32, 64, 128],
        center_sampling=True,
        center_sample_radius=1.5,
        norm_on_bbox=True,
        centerness_on_reg=True,
        separate_angle=False,
        scale_angle=True,
        bbox_coder=dict(type='DistanceAnglePointCoder', angle_version='le90'),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='RotatedIoULoss', loss_weight=1.0),
        loss_centerness=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
    train_cfg=None,
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))
angle_version = 'le90'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
dataset_type = 'DebugDOTADataset'
src_data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='DebugDOTADataset',
        ann_file='data/split_ss_dota_v15/train/annfiles/',
        img_prefix='data/split_ss_dota_v15/train/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='RResize', img_scale=(1024, 1024)),
            dict(type='RRandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')),
    val=dict(
        type='DebugDOTADataset',
        ann_file='data/split_ss_dota_v15/val/annfiles/',
        img_prefix='data/split_ss_dota_v15/val/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')),
    test=dict(
        type='DebugDOTADataset',
        ann_file='data/split_ss_dota_v15/val/annfiles/',
        img_prefix='data/split_ss_dota_v15/val/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')))
custom_imports = dict(imports=['ssad'], allow_failed_imports=False)
sup_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version='le90'),
    dict(type='ExtraAttrs', tag='sup_weak'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels'],
        meta_keys=('filename', 'ori_filename', 'ori_shape', 'img_shape',
                   'pad_shape', 'scale_factor', 'flip', 'flip_direction',
                   'img_norm_cfg', 'tag'))
]
common_pipeline = [
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels'],
        meta_keys=('filename', 'ori_filename', 'ori_shape', 'img_shape',
                   'pad_shape', 'scale_factor', 'flip', 'flip_direction',
                   'img_norm_cfg', 'tag'))
]
strong_pipeline = [
    dict(type='DTToPILImage'),
    dict(
        type='DTRandomApply',
        operations=[
            ColorJitter(
                brightness=[0.6, 1.4],
                contrast=[0.6, 1.4],
                saturation=[0.6, 1.4],
                hue=[-0.1, 0.1])
        ],
        p=0.8),
    dict(type='DTRandomGrayscale', p=0.2),
    dict(
        type='DTRandomApply',
        operations=[dict(type='DTGaussianBlur', rad_range=[0.1, 2.0])]),
    dict(type='DTToNumpy'),
    dict(type='ExtraAttrs', tag='unsup_strong')
]
weak_pipeline = [
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version='le90'),
    dict(type='ExtraAttrs', tag='unsup_weak')
]
unsup_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadEmptyAnnotations', with_bbox=True),
    dict(
        type='STMultiBranch',
        unsup_strong=[
            dict(type='DTToPILImage'),
            dict(
                type='DTRandomApply',
                operations=[
                    ColorJitter(
                        brightness=[0.6, 1.4],
                        contrast=[0.6, 1.4],
                        saturation=[0.6, 1.4],
                        hue=[-0.1, 0.1])
                ],
                p=0.8),
            dict(type='DTRandomGrayscale', p=0.2),
            dict(
                type='DTRandomApply',
                operations=[dict(type='DTGaussianBlur', rad_range=[0.1,
                                                                   2.0])]),
            dict(type='DTToNumpy'),
            dict(type='ExtraAttrs', tag='unsup_strong')
        ],
        unsup_weak=[
            dict(type='RResize', img_scale=(1024, 1024)),
            dict(
                type='RRandomFlip',
                flip_ratio=[0.25, 0.25, 0.25],
                direction=['horizontal', 'vertical', 'diagonal'],
                version='le90'),
            dict(type='ExtraAttrs', tag='unsup_weak')
        ],
        common_pipeline=[
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels'],
                meta_keys=('filename', 'ori_filename', 'ori_shape',
                           'img_shape', 'pad_shape', 'scale_factor', 'flip',
                           'flip_direction', 'img_norm_cfg', 'tag'))
        ],
        is_seq=True)
]
data = dict(
    samples_per_gpu=3,
    workers_per_gpu=3,
    train=dict(
        type='SemiDataset',
        sup=dict(
            type='DebugDOTADataset',
            ann_file='data/split_ss_dota_v15/train_10_labeled/annfiles/',
            img_prefix='data/split_ss_dota_v15/train_10_labeled/images/',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(type='RResize', img_scale=(1024, 1024)),
                dict(
                    type='RRandomFlip',
                    flip_ratio=[0.25, 0.25, 0.25],
                    direction=['horizontal', 'vertical', 'diagonal'],
                    version='le90'),
                dict(type='ExtraAttrs', tag='sup_weak'),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[58.395, 57.12, 57.375],
                    to_rgb=True),
                dict(type='Pad', size_divisor=32),
                dict(type='DefaultFormatBundle'),
                dict(
                    type='Collect',
                    keys=['img', 'gt_bboxes', 'gt_labels'],
                    meta_keys=('filename', 'ori_filename', 'ori_shape',
                               'img_shape', 'pad_shape', 'scale_factor',
                               'flip', 'flip_direction', 'img_norm_cfg',
                               'tag'))
            ],
            classes=('plane', 'baseball-diamond', 'bridge',
                     'ground-track-field', 'small-vehicle', 'large-vehicle',
                     'ship', 'tennis-court', 'basketball-court',
                     'storage-tank', 'soccer-ball-field', 'roundabout',
                     'harbor', 'swimming-pool', 'helicopter',
                     'container-crane')),
        unsup=dict(
            type='DebugDOTADataset',
            ann_file=
            'data/split_ss_dota_v15/train_10_unlabeled/empty_annfiles/',
            img_prefix='data/split_ss_dota_v15/train_10_unlabeled/images/',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadEmptyAnnotations', with_bbox=True),
                dict(
                    type='STMultiBranch',
                    unsup_strong=[
                        dict(type='DTToPILImage'),
                        dict(
                            type='DTRandomApply',
                            operations=[
                                ColorJitter(
                                    brightness=[0.6, 1.4],
                                    contrast=[0.6, 1.4],
                                    saturation=[0.6, 1.4],
                                    hue=[-0.1, 0.1])
                            ],
                            p=0.8),
                        dict(type='DTRandomGrayscale', p=0.2),
                        dict(
                            type='DTRandomApply',
                            operations=[
                                dict(
                                    type='DTGaussianBlur',
                                    rad_range=[0.1, 2.0])
                            ]),
                        dict(type='DTToNumpy'),
                        dict(type='ExtraAttrs', tag='unsup_strong')
                    ],
                    unsup_weak=[
                        dict(type='RResize', img_scale=(1024, 1024)),
                        dict(
                            type='RRandomFlip',
                            flip_ratio=[0.25, 0.25, 0.25],
                            direction=['horizontal', 'vertical', 'diagonal'],
                            version='le90'),
                        dict(type='ExtraAttrs', tag='unsup_weak')
                    ],
                    common_pipeline=[
                        dict(
                            type='Normalize',
                            mean=[123.675, 116.28, 103.53],
                            std=[58.395, 57.12, 57.375],
                            to_rgb=True),
                        dict(type='Pad', size_divisor=32),
                        dict(type='DefaultFormatBundle'),
                        dict(
                            type='Collect',
                            keys=['img', 'gt_bboxes', 'gt_labels'],
                            meta_keys=('filename', 'ori_filename', 'ori_shape',
                                       'img_shape', 'pad_shape',
                                       'scale_factor', 'flip',
                                       'flip_direction', 'img_norm_cfg',
                                       'tag'))
                    ],
                    is_seq=True)
            ],
            filter_empty_gt=False,
            classes=('plane', 'baseball-diamond', 'bridge',
                     'ground-track-field', 'small-vehicle', 'large-vehicle',
                     'ship', 'tennis-court', 'basketball-court',
                     'storage-tank', 'soccer-ball-field', 'roundabout',
                     'harbor', 'swimming-pool', 'helicopter',
                     'container-crane'))),
    val=dict(
        type='DebugDOTADataset',
        ann_file='data/split_ss_dota_v15/val/annfiles/',
        img_prefix='data/split_ss_dota_v15/val/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')),
    test=dict(
        type='DebugDOTADataset',
        ann_file='data/split_ss_dota_v15/val/annfiles/',
        img_prefix='data/split_ss_dota_v15/val/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')),
    sampler=dict(
        train=dict(type='GroupMultiSourceSampler', sample_ratio=[2, 1])))
model = dict(
    type='RotatedSSTGDenseTeacher',
    model=dict(
        type='SemiRotatedFCOS',
        backbone=dict(
            type='ResNet',
            depth=50,
            num_stages=4,
            out_indices=(0, 1, 2, 3),
            frozen_stages=1,
            zero_init_residual=False,
            norm_cfg=dict(type='BN', requires_grad=True),
            norm_eval=True,
            style='pytorch',
            init_cfg=dict(
                type='Pretrained', checkpoint='torchvision://resnet50')),
        neck=dict(
            type='FPN',
            in_channels=[256, 512, 1024, 2048],
            out_channels=256,
            start_level=1,
            add_extra_convs='on_output',
            num_outs=5,
            relu_before_extra_convs=True),
        bbox_head=dict(
            type='SemiRotatedFCOSHead',
            num_classes=16,
            in_channels=256,
            stacked_convs=4,
            feat_channels=256,
            strides=[8, 16, 32, 64, 128],
            center_sampling=True,
            center_sample_radius=1.5,
            norm_on_bbox=True,
            centerness_on_reg=True,
            separate_angle=False,
            scale_angle=True,
            bbox_coder=dict(
                type='DistanceAnglePointCoder', angle_version='le90'),
            loss_cls=dict(
                type='FocalLoss',
                use_sigmoid=True,
                gamma=2.0,
                alpha=0.25,
                loss_weight=1.0),
            loss_bbox=dict(type='RotatedIoULoss', loss_weight=1.0),
            loss_centerness=dict(
                type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
        train_cfg=None,
        test_cfg=dict(
            nms_pre=2000,
            min_bbox_size=0,
            score_thr=0.05,
            nms=dict(iou_thr=0.1),
            max_per_img=2000)),
    semi_loss=dict(
        type='RotatedSingleStageDTLoss',
        loss_type='pr_origin_p5',
        cls_loss_type='bce',
        dynamic_weight='50ang',
        aux_loss='ot_loss_norm',
        aux_loss_cfg=dict(clamp_ot=True)),
    train_cfg=dict(
        iter_count=0,
        burn_in_steps=6400,
        sup_weight=1.0,
        unsup_weight=1.0,
        weight_suppress='linear',
        logit_specific_weights=dict(),
        region_ratio=0.01),
    test_cfg=dict(inference_on='teacher'))
custom_hooks = [
    dict(type='NumClassCheckHook'),
    dict(type='WeightSummary'),
    dict(type='MeanTeacher', momentum=0.9996, interval=1, start_steps=3200)
]
data_root = 'data/split_ss_dota_v15/'
classes = ('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
           'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
           'basketball-court', 'storage-tank', 'soccer-ball-field',
           'roundabout', 'harbor', 'swimming-pool', 'helicopter',
           'container-crane')
work_dir = 'sood_result/sood_fcos_dota15_10per_ori-lr'
auto_resume = False
gpu_ids = range(0, 2)

2023-08-23 23:23:10,673 - mmrotate - INFO - Set random seed to 42, deterministic: True
2023-08-23 23:23:11,433 - mmrotate - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet50'}
2023-08-23 23:23:11,433 - mmcv - INFO - load model from: torchvision://resnet50
2023-08-23 23:23:11,433 - mmcv - INFO - load checkpoint from torchvision path: torchvision://resnet50
2023-08-23 23:23:11,640 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2023-08-23 23:23:11,672 - mmrotate - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2023-08-23 23:23:11,702 - mmrotate - INFO - initialize SemiRotatedFCOSHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01, 'override': {'type': 'Normal', 'name': 'conv_cls', 'std': 0.01, 'bias_prob': 0.01}}
2023-08-23 23:23:11,780 - mmrotate - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet50'}
2023-08-23 23:23:11,781 - mmcv - INFO - load model from: torchvision://resnet50
2023-08-23 23:23:11,781 - mmcv - INFO - load checkpoint from torchvision path: torchvision://resnet50
2023-08-23 23:23:11,994 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2023-08-23 23:23:12,028 - mmrotate - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2023-08-23 23:23:12,057 - mmrotate - INFO - initialize SemiRotatedFCOSHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01, 'override': {'type': 'Normal', 'name': 'conv_cls', 'std': 0.01, 'bias_prob': 0.01}}
2023-08-23 23:23:14,757 - mmrotate - INFO - Start running, host: dell@dell, work_dir: sood_result/sood_fcos_dota15_10per_ori-lr
2023-08-23 23:23:14,757 - mmrotate - INFO - Hooks will be executed in the following order:

And the best mAPs are:
+--------------------+-------+--------+--------+-------+
| class              | gts   | dets   | recall | ap    |
+--------------------+-------+--------+--------+-------+
| plane              | 4478  | 11483  | 0.810  | 0.755 |
| baseball-diamond   | 354   | 1829   | 0.630  | 0.488 |
| bridge             | 788   | 7672   | 0.180  | 0.121 |
| ground-track-field | 214   | 3484   | 0.350  | 0.172 |
| small-vehicle      | 73488 | 251778 | 0.457  | 0.331 |
| large-vehicle      | 10284 | 86303  | 0.624  | 0.408 |
| ship               | 21783 | 58222  | 0.763  | 0.672 |
| tennis-court       | 1515  | 4562   | 0.844  | 0.782 |
| basketball-court   | 287   | 1019   | 0.366  | 0.257 |
| storage-tank       | 4819  | 11761  | 0.528  | 0.473 |
| soccer-ball-field  | 243   | 1723   | 0.346  | 0.246 |
| roundabout         | 287   | 2723   | 0.589  | 0.389 |
| harbor             | 4185  | 21214  | 0.353  | 0.155 |
| swimming-pool      | 997   | 16239  | 0.585  | 0.393 |
| helicopter         | 128   | 2082   | 0.336  | 0.143 |
| container-crane    | 28    | 1119   | 0.000  | 0.000 |
+--------------------+-------+--------+--------+-------+
| mAP                |       |        |        | 0.362 |
+--------------------+-------+--------+--------+-------+
+--------------------+-------+--------+--------+-------+
| class              | gts   | dets   | recall | ap    |
+--------------------+-------+--------+--------+-------+
| plane              | 4478  | 10434  | 0.809  | 0.759 |
| baseball-diamond   | 354   | 1455   | 0.613  | 0.488 |
| bridge             | 788   | 6894   | 0.175  | 0.124 |
| ground-track-field | 214   | 3494   | 0.346  | 0.179 |
| small-vehicle      | 73488 | 280822 | 0.457  | 0.327 |
| large-vehicle      | 10284 | 86550  | 0.613  | 0.405 |
| ship               | 21783 | 66853  | 0.763  | 0.662 |
| tennis-court       | 1515  | 4909   | 0.837  | 0.778 |
| basketball-court   | 287   | 1001   | 0.348  | 0.262 |
| storage-tank       | 4819  | 11110  | 0.537  | 0.480 |
| soccer-ball-field  | 243   | 1808   | 0.350  | 0.246 |
| roundabout         | 287   | 2567   | 0.575  | 0.386 |
| harbor             | 4185  | 21220  | 0.345  | 0.152 |
| swimming-pool      | 997   | 14423  | 0.560  | 0.385 |
| helicopter         | 128   | 1892   | 0.336  | 0.116 |
| container-crane    | 28    | 994    | 0.000  | 0.000 |
+--------------------+-------+--------+--------+-------+
| mAP                |       |        |        | 0.359 |
+--------------------+-------+--------+--------+-------+

2023-08-25 05:50:12,956 - mmrotate - INFO - Iter(val) [118400]	teacher.mAP: 0.3616, student.mAP: 0.3592
2023-08-25 05:50:45,526 - mmrotate - INFO - Iter [118450/120000]	lr: 2.500e-05, eta: 0:23:54, time: 7.709, data_time: 7.071, memory: 5528, loss_cls_sup: 0.1307, loss_bbox_sup: 0.3255, loss_centerness_sup: 0.6169, loss_raw_unsup: 0.3679, loss_gc_unsup: 0.0000, loss: 1.4409, grad_norm: 15.0634

**What issues are there with my configuration?** @HamPerdredes

**Comment by HamPerdredes** [comment]
I can't tell what cause this issue from the provided information. The results seems even lower than supervised baseline. Please follow [here](https://github.com/HamPerdredes/SOOD/issues/6#issuecomment-1594147104) to do a double check and let me know if that solves the problem.
